server:
  servlet:
    context-path: /home-security/v1

stream:
  model:
    baseUrl: "http://download.tensorflow.org/models/object_detection/tf2"
    name: "ssd_mobilenet_v2_320x320_coco17_tpu-8"
    date: "20200711"

  label:
    baseUrl: 'https://raw.githubusercontent.com/tensorflow/models/master/research/object_detection/data'
    name: 'mscoco_label_map.pbtxt'

  sources:
    - id: 0
      port: 5555
      queueSize: 5
    - id: 1
      port: 5556
      queueSize: 5